apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: givebackcincinnati
  namespace: prod
spec:
  secretName: givebackcincinnati-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - 'givebackcincinnati.org'
  - '*.givebackcincinnati.org'