apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: studyhall
  namespace: stage
spec:
  secretName: studyhall-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - 'studyhall.dev'
  - '*.studyhall.dev'