apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: studyhall
  namespace: vault
spec:
  secretName: studyhall-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - 'vault.studyhall.org'